# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_dadospessoais_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='nome',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
        ),
    ]
